
Table food {
  id NUMBER PK
	item VARCHAR
	veg BOOLEAN
}

Table restaurant {
  id NUMBER PK
  name VARCHAR
  city VARCHAR
  rating NUMBER
  rating_cnt NUMBER
  cost VARCHAR
  cuisine VARCHAR
  lic_no NUMBER
  link VARCHAR
}

Table users {
  id INTEGER PK
  name VARCHAR
  email VARCHAR
  password VARCHAR
  age NUMBER
  gender VARCHAR
  marital_status BOOLEAN
  occupation VARCHAR
  monthly_income NUMBER
  educational_qualifications VARCHAR
  family_size NUMBER
}

Table menu {
  id NUMBER PK
  rid NUMBER
  fid NUMBER
  cuisine VARCHAR
  price FLOAT
}

Table orders {
  order_date DATE
  uid NUMBER
  rid NUMBER
  sales_qty NUMBER
  sales_amt NUMBER
  currency VARCHAR
}


Ref: food.id < menu.fid

Ref: restaurant.id < menu.rid

//Ref: restaurant.cuisine <> menu.cuisine

Ref: restaurant.id < orders.rid

//Ref: orders.rid <> menu.rid

Ref: users.id < orders.uid
